TheWorld/Models/Trip.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace TheWorld.Models
{
  public class Trip
  {
    public int Id { get; set; }
    public string Name { get; set; }
    public DateTime DateCreated { get; set; }
    public string UserName { get; set; }

    public ICollection<Stop> Stops { get; set; }
  }
}

TheWorld/ViewModels/ContactViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace TheWorld.ViewModels
{
  public class ContactViewModel
  {
    [Required]
    public string Name { get; set; }

    [Required]
    [EmailAddress]
    public string Email { get; set; }

    [Required]
    [StringLength(4096, MinimumLength = 10)]
    public string Message { get; set; }
  }
}

TheWorld/ViewModels/TripViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace TheWorld.ViewModels
{
  public class TripViewModel
  {
    [Required]
    [StringLength(100, MinimumLength = 5)]
    public string Name { get; set; }
    public DateTime DateCreated { get; set; } = DateTime.UtcNow;
  }
}

TheWorld/Controllers/Api/TripsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using TheWorld.Models;
using TheWorld.ViewModels;

namespace TheWorld.Controllers.Api
{
  [Route("api/trips")]
  [Authorize]
  public class TripsController : Controller
  {
    private ILogger<TripsController> _logger;
    private IWorldRepository _repository;

    public TripsController(IWorldRepository repository, ILogger<TripsController> logger)
    {
      _repository = repository;
      _logger = logger;
    }

    [HttpGet("")]
    public IActionResult Get()
    {
      try
      {
        var results = _repository.GetTripsByUsername(User.Identity.Name);

        return Ok(Mapper.Map<IEnumerable<TripViewModel>>(results));
      }
      catch (Exception ex)
      {
        _logger.LogError($"Failed to get All Trips: {ex}");

        return BadRequest("Error occurred");
      }
    }

    [HttpPost("")]
    public async Task<IActionResult> Post([FromBody]TripViewModel theTrip)
    {
      if (ModelState.IsValid)
      {
        // Save to the Database
        var newTrip = Mapper.Map<Trip>(theTrip);

        newTrip.UserName = User.Identity.Name;

        _repository.AddTrip(newTrip);

        if (await _repository.SaveChangesAsync())
        {
          return Created($"api/trips/{theTrip.Name}", Mapper.Map<TripViewModel>(newTrip));
        }
      }

      return BadRequest("Failed to save the trip");
    }
  }
}

TheWorld/Controllers/Web/AppController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Logging;
using TheWorld.Models;
using TheWorld.Services;
using TheWorld.ViewModels;

namespace TheWorld.Controllers.Web
{
  public class AppController : Controller
  {
    private IMailService _mailService;
    private IConfigurationRoot _config;
    private IWorldRepository _repository;
    private ILogger<AppController> _logger;

    public AppController(IMailService mailService, 
      IConfigurationRoot config, 
      IWorldRepository repository,
      ILogger<AppController> logger)
    {
      _mailService = mailService;
      _config = config;
      _repository = repository;
      _logger = logger;
    }

    public IActionResult Index()
    {
      return View();
    }

    [Authorize]
    public IActionResult Trips()
    {
      try
      {

        return View();
      }
      catch (Exception ex)
      {
        _logger.LogError($"Failed to get trips in Index page: {ex.Message}");
        return Redirect("/error");
      }
    }

    public IActionResult Contact()
    {
      return View();
    }

    [HttpPost]
    public IActionResult Contact(ContactViewModel model)
    {
      if (model.Email.Contains("aol.com"))
      {
        ModelState.AddModelError("", "We don't support AOL addresses");
      }

      if (ModelState.IsValid)
      {
        _mailService.SendMail(_config["MailSettings:ToAddress"], model.Email, "From TheWorld", model.Message);

        ModelState.Clear();

        ViewBag.UserMessage = "Message Sent";
      }

      return View();
    }

    public IActionResult About()
    {
      return View();
    }

  }
}

TheWorld/Views/App/About.cshtml
@{
  ViewBag.Title = "About Page";
}
<h2>About The World</h2>

TheWorld/Views/App/Contact.cshtml
@model TheWorld.ViewModels.ContactViewModel
@{
  ViewBag.Title = "Contact Page";
}

@section scripts {
  <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
  <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
}
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <h2>Contact</h2>
    <form method="post">
      @if (ViewBag.Message != null)
      {
        <div>@ViewBag.Message</div>
      }
      <div asp-validation-summary="ModelOnly"></div>
      <div class="form-group">
        <label asp-for="Name">Name</label>
        <input asp-for="Name" class="form-control" />
        <span asp-validation-for="Name" class="text-muted"></span>
      </div>
      <div class="form-group">
        <label asp-for="Email">Email</label>
        <input type="email" asp-for="Email" class="form-control" />
        <span asp-validation-for="Email" class="text-muted"></span>
      </div>
      <div class="form-group">
        <label asp-for="Message">Message</label>
        <textarea cols="40" rows="4" asp-for="Message" class="form-control"></textarea>
        <span asp-validation-for="Message" class="text-muted"></span>
      </div>
      <div class="form-group">
        <a asp-controller="App" asp-action="Index" class="btn btn-default">Cancel</a>
        <input type="submit" value="Send Message" class="btn btn-success" />
      </div>
    </form>
  </div>
</div>

TheWorld/Views/App/Index.cshtml
@model IEnumerable<TheWorld.Models.Trip>
@{
  ViewBag.Title = "Home Page";
}
<div class="row">
  <div class="col-lg-12">
    <h1>Welcome to The World</h1>
    <p>This is a web app that will help you build world trips.</p>
    <a asp-controller="App" asp-action="Trips" class="btn btn-lg btn-success">Goto Your Trips</a>
  </div>
</div>

TheWorld/Views/App/Trips.cshtml
@{
  ViewBag.Title = "Home Page";
}
@section Scripts {
    <script src="~/lib/underscore/underscore-min.js"></script>
  <script src="~/lib/angular/angular.min.js"></script>
  <script src="~/lib/angular-route/angular-route.min.js"></script>
<script src="http://maps.google.com/maps/api/js?sensor=true"></script>
    <script src="~/lib/gmaps/gmaps.min.js"></script>
    <script src="~/lib/travelmap/travelmap.min.js"></script>
  <script src="~/js/simpleControls.js"></script>
  <script src="~/js/app-trips.js"></script>
  <script src="~/js/tripsController.js"></script>
<script src="~/js/tripEditorController.js"></script>
}
<div class="row" ng-app="app-trips">

    <div data-ng-view></div>

  @*<div ng-controller="tripsController as vm" class="col-md-6 col-md-offset-3">
    <div class="text-danger" ng-show="vm.errorMessage">{{ vm.errorMessage }}</div>
    <wait-cursor display-when="vm.isBusy"></wait-cursor>
    <table class="table table-responsive table-striped">
      <tr ng-repeat="trip in vm.trips">
        <td>{{ trip.name }}</td>
        <td>{{ trip.created | date:'MM-dd-yyyy' }}</td>
        <td><a href="#" class="btn btn-sm btn-primary">Manage</a></td>
      </tr>
    </table>

    <form novalidate name="newTripForm" ng-submit="vm.addTrip()">
      <div class="form-group">
        <label for="name">Trip Name</label>
        <input class="form-control" type="text" id="name" name="name" ng-model="vm.newTrip.name" required ng-minlength="5" />
        <span ng-show="newTripForm.name.$error.required" class="text-warning">Name is required.</span>
        <span ng-show="newTripForm.name.$error.minlength" class="text-warning">Name must be at least five characters.</span>
      </div>
      <div class="form-group">
        <input type="submit" value="Add"
               class="btn btn-success btn-sm"
               ng-disabled="newTripForm.$invalid" />
      </div>
    </form>

  </div>*@

  @*<div class="col-md-6">
    <h2>The Map</h2>

    <ul>
      @foreach (var item in Model)
      {
        <li>@item.Name : @item.DateCreated.ToString("d")</li>
      }
    </ul>

  </div>*@

</div>